version: '3.7'

services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment: 
      - DOMAIN=michibaum.ch
      - EMAIL=michael_baumberger@gmx.ch
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - reverse-proxy-network

networks:
  reverse-proxy-network:
      name: reverse-proxy-network
      driver: bridge