version: '3.7'

services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - /docker/reverse-proxy/logs:/var/log/nginx
      - /docker/reverse-proxy/certificates:/usr/share/nginx/certificates
    networks: 
      - reverse-proxy-network

networks:
  reverse-proxy-network:
      name: reverse-proxy-network
      driver: bridge