version: '3.7'

services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - '80:80'
      - '443:443'
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - reverse-proxy-network
    volumes: 
      - /docker/reverse-proxy/logs/:/var/log/nginx/
      - /docker/certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /docker/certbot/conf:/etc/letsencrypt


networks:
  reverse-proxy-network:
      name: reverse-proxy-network
      driver: bridge